/**
 * The /api/dsh-desktop-launcher/restart route: a loopback-only control
 * surface that asks the host process to restart. The response is written
 * first and the restart is dispatched a short beat later so the browser
 * receives the acknowledgement before the process tears down.
 *
 * Restart strategy:
 * 1. When the process runs under systemd (default unit `dsh.service`,
 *    overridable via the DSH_RESTART_UNIT environment variable), execute
 *    `systemctl restart <unit>` and let systemd bring dsh back.
 * 2. Otherwise fall back to a detached relaunch: write a small
 *    dsh-relaunch.cjs script (under $DSH_DESKTOP_LAUNCHER_RESTART_DIR when
 *    set, else a temp dir) that spawns the same node/dsh command line again,
 *    then request a bounded exit (ctx.appExit, process.exit fallback).
 */

import { execFile, spawn } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path/posix'
import { promisify } from 'node:util'
import type { IncomingMessage } from 'node:http'
import type { WebRoute } from '@deepseek-ai/dsh-host-webserver'
import { LAUNCHER_API } from './protocol.ts'
import { isLoopbackRequest } from './loopback.ts'
import { writeJson } from './http.ts'

const execFileAsync = promisify(execFile)

/** How long the restart waits after the response is flushed. */
export const RESTART_DELAY_MS = 600

export { isLoopbackRequest }

/** Route-family dependencies (test seam). */
export interface RestartRouteDeps {
  /** Loopback-only fence: the control endpoint is host-surface only. */
  fence(request: IncomingMessage): boolean
  /** Request the bounded process exit (ctx.appExit, process.exit fallback). */
  requestExit(code: number): void
  /** Schedule the restart after the response; defaults to setTimeout. */
  schedule?: (fn: () => void, ms: number) => unknown
  /** systemd unit to restart; defaults to $DSH_RESTART_UNIT or dsh.service. */
  unit?: string
}

/**
 * Read the machine-readable dsh command line of the current process.
 * @returns the argv array (node, script, ...args) or undefined.
 */
export function currentDshArgv(): string[] | undefined {
  try {
    const line = readFileSync('/proc/self/cmdline', 'utf8')
    const parts = line.split('\0').filter((part) => part.length > 0)
    if (parts.length >= 2 && /node(?:\.|$)/.test(parts[0])) {
      const script = parts[1]
      if (/dsh(?:$|\/|\.)/.test(script)) return parts
    }
  } catch {
    /* not Linux or unreadable; caller falls back to 'dsh web --no-open' */
  }
  return undefined
}

/**
 * Build a detached relaunch script that starts dsh again with the same
 * arguments, without ever returning.
 * @returns the script text, or undefined when the process command line is
 *   not a recognizable dsh invocation.
 */
export function relaunchScript(): string | undefined {
  const argv = currentDshArgv()
  if (argv === undefined || argv.length < 3) return undefined
  const [node, script, ...args] = argv
  const relauncher = [
    '#!/usr/bin/env node',
    '// dsh detached relaunch (generated by dsh-desktop-launcher restart)',
    'const { spawn } = require("node:child_process");',
    `const nodePath = ${JSON.stringify(node)};`,
    `const scriptPath = ${JSON.stringify(script)};`,
    `const args = ${JSON.stringify(args)};`,
    'const child = spawn(nodePath, [scriptPath, ...args], {',
    '  detached: true,',
    '  stdio: "ignore",',
    '  windowsHide: true',
    '});',
    'child.unref();',
    'setTimeout(() => process.exit(0), 500);',
    '',
  ].join('\n')
  try {
    const dir = process.env.DSH_DESKTOP_LAUNCHER_RESTART_DIR
    if (dir !== undefined && dir !== '') {
      const file = join(dir, 'dsh-relaunch.cjs')
      writeFileSync(file, relauncher, 'utf8')
      return file
    }
  } catch {
    /* fall through to the temp dir */
  }
  try {
    const dir = mkdtempSync(join(tmpdir(), 'dsh-relaunch-'))
    const file = join(dir, 'dsh-relaunch.cjs')
    writeFileSync(file, relauncher, 'utf8')
    return file
  } catch {
    return undefined
  }
}

/**
 * Restart the host process: request a systemd restart of the dsh unit when
 * this process runs inside one, otherwise exit and let a detached relaunch
 * bring dsh back.
 * @returns the restart dispatch result.
 */
export async function performRestart(deps: RestartRouteDeps): Promise<{ ok: true; via: string; unit?: string }> {
  const unit = deps.unit ?? process.env.DSH_RESTART_UNIT ?? 'dsh.service'
  if (unit !== '') {
    try {
      await execFileAsync('systemctl', ['restart', unit], { timeout: 15000, windowsHide: true })
      return { ok: true, via: 'systemctl', unit }
    } catch (error) {
      if (typeof error === 'object' && error !== null && 'code' in error && (error as { code?: unknown }).code === 'ENOENT') {
        // systemctl is not available; fall through to the detached relaunch path.
      } else {
        throw error
      }
    }
  }
  // Fallback: ask the launcher for a bounded exit, then start dsh again from
  // a detached child that survives this process.
  const relauncher = relaunchScript()
  if (relauncher !== undefined) {
    spawn(process.execPath, [relauncher], {
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
    }).unref()
  }
  deps.requestExit(0)
  return { ok: true, via: 'exit+relaunch' }
}

/**
 * Build the restart route.
 * @param deps - fence + exit seam (and an optional schedule seam for tests).
 * @returns the exact route to register on webServer.
 */
export function makeRestartRoute(deps: RestartRouteDeps): WebRoute {
  const schedule = deps.schedule ?? ((fn: () => void, ms: number) => setTimeout(fn, ms))
  return {
    kind: 'exact',
    path: LAUNCHER_API.restart,
    handler: async (req, res) => {
      if ((req.method ?? 'GET') !== 'POST') {
        writeJson(res, 405, { error: `method not allowed: ${req.method}` })
        return
      }
      if (!deps.fence(req)) {
        writeJson(res, 403, { error: 'forbidden: loopback-only' })
        return
      }
      writeJson(res, 200, { ok: true })
      // Flush first: the browser must see the acknowledgement before the
      // process is gone. Leave enough time for fetch to settle before the
      // restart dispatches.
      schedule(() => {
        void performRestart(deps).catch((error) => {
          console.error('[dsh-desktop-launcher] restart failed:', error)
        })
      }, RESTART_DELAY_MS)
    },
  }
}
